Add support for STREEBOG hashing algorithm
CycloneDX/specification pull request #525
Opened 2024-09-26 14:03 UTC by volkdm

Closes #485

2024-09-26 14:11 UTC, jkowalleck requested changes
please write the name "Streebog", not in all caps "STREEBOG".
Unlike SHA, BLAKE, MD5, Streebog is not an abbreviation, but a name.

2024-09-26 14:24 UTC, jkowalleck requested changes

2024-09-26 14:24 UTC, jkowalleck commented on schema/bom-1.7.schema.json
> +        "STREEBOG-256",
```patch
- "STREEBOG-256",
- "STREEBOG-512"
+ "Streebog-256",
+ "Streebog-512"
```

2024-09-26 14:24 UTC, jkowalleck commented on schema/bom-1.7.xsd
> +            <xs:enumeration value="STREEBOG-256"/>
```patch
- <xs:enumeration value="STREEBOG-256"/>
- <xs:enumeration value="STREEBOG-512"/>
+ <xs:enumeration value="Streebog-256"/>
+ <xs:enumeration value="Streebog-512"/>

2024-09-26 14:24 UTC, jkowalleck commented on schema/bom-1.7.proto
> +  STREEBOG_256 = 13;
```patch
- STREEBOG_256 = 13;
- STREEBOG_512 = 14;
+ HASH_ALG_STREEBOG_256 = 13;
+ HASH_ALG_STREEBOG_512 = 14;
```

2024-09-26 15:15 UTC, jkowalleck approved these changes

2024-10-01 03:01 UTC, stevespringett approved these changes

2024-10-01 03:06 UTC, stevespringett commented
The official RFC notice has been published and will be open until October 28. If approved, it will be promoted to Ecma TC54.

2025-03-16 08:47 UTC, merged